import React from 'react'

export const metadata = {
    title: "Travelo | About Us",
    description: "Generated by create next app",
    icons: {
        icon: "/logo/Vector.png", // your logo or favicon path
    },
};

export default function AboutPage() {
    return (
        <div>
            asfgsadf
        </div>
    )
}
