import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";
import ScrollTop from "./Components/ScrollTop";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Travelo",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/Vector.png", // your logo or favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Navbar/>
        </header>
        <div className="min-h-[calc(100vh - 230px)]">
          {children}
        </div>
        <ScrollTop/>
        <Footer/>
      </body>
    </html>
  );
}
